### ISSUE TITLE
artifactcollector detected as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by meeehow** [forensicanalysis/artifactcollector#165]
I compiled a new artifactcollector binary (from head) and it seems that Windows Defender detects it as Trojan:Win32/Wacatac.B!ml

**Comment by cugu** [comment]
Thanks for the report! 

The artifactcollector binary collects a bunch of sensitive files and usually requests admin privileges, so I am not surprised that Defender does not like it. If you are running it in an enterprise environment, you should be able to allow this binary or send it to Microsoft for reevaluation.
