### ISSUE TITLE
Improve collection time

### ISSUE THREAD

**Issue by tatsu-i** [forensicanalysis/artifactcollector#32]
By creating item.db, it may take time to get artifacts.
Is there an option to skip hash calculation or not create item.db for speeding up?

**Comment by cugu** [comment]
I did some testing with disabling the hash calculation and the item.db insertion. The run times were pretty much the same as with those features enabled.

The artifactcollector with default artifacts takes 7-9 minutes on my system.

Does the artifactcollector take too long in you case?

You can have a look in the created log file which artifacts take longer to collect.

**Comment by tatsu-i** [comment]
So that's it

So where is the bottleneck that takes 7 minutes?
I guess the size is such that if you just copy the file, it will take about one minute.

**Comment by cugu** [comment]
Most time is used for the Chrome Cache in my case. There are about 2,000 files for that artifact. 

A simple copy for all the files takes about 30s, but the artifactcollector also needs to resolve artifacts, replace variables, search the artifacts and the copy itself might not be as efficient as `cp`.

Step | Duration in Seconds
:-- | --:
_Setup_ | _7_
SafariDownloads | 1,3
WindowsSystemResourceUsageMonitorDatabaseFile | 1,6
InternetExplorerHistory | 28,3
WindowsRecycleBin | 1,3
WindowsOpenSaveMRU | 0
SafariCache | 0,4
FirefoxCache | 0
WindowsAppCompatCache | 0
FirefoxHistory | 1,2
ChromeCache | 233,9
OperaHistory | 0,7
WindowsTimezone | 0
WindowsSetupApiLogs | 0,5
WindowsMostRecentApplication | 0
ChromeHistory | 87,3
WindowsSystemRegistryFiles | 66,2
WindowsPrefetchFiles | 14,4
InternetExplorerCache | 3,8
SafariHistory | 1,7
WindowsXMLEventLogSecurity | 1,4
WindowsActivitiesCache | 1,7
WindowsAMCacheHveFile | 2,2
InternetExplorerCookies | 3,2
_Compression_ | _33_
**Total** | **492**

**Comment by cugu** [comment]
I'm closing this for now. Performance can always be improved, but is not in focus currently.
