### ISSUE TITLE
Collect directly to zip

### ISSUE THREAD

**Issue by cugu** [forensicanalysis/artifactcollector#5]

**Comment by ilyaglow** [comment]
I think I can try to implement this one.

Would you like to make it as a kinda limited filesystem abstraction based on [spf13/afero](https://github.com/spf13/afero) or incorporate it as a set of functions in [JSONLite](https://github.com/forensicanalysis/forensicstore/blob/master/gojsonlite/jsonlite.go) store struct?

**Comment by cugu** [comment]
The rough idea is to set the `Fs` in the JSONLite to https://github.com/forensicanalysis/fslib/tree/master/aferotools/zipwrite and add the database when done. Also some of the `local*` fields might need to be changed. 

But this might yield some problems when reading items for provides.
