### ISSUE TITLE
Unable to collect locked files

### ISSUE THREAD

**Issue by tatsu-i** [forensicanalysis/artifactcollector#50]
I cannot get the file even though I have administrator privileges.
Is there a way to get locked files like OST?

```
name: DefaultEntryPoint
doc: Windows Forensic Analysis
sources:
- type: ARTIFACT_GROUP
  attributes:
    names:
    - Mail
  supported_os: [Windows]
supported_os: [Windows]

---
name: Mail
doc: Email Files
sources:
- type: FILE
  attributes:
    paths: 
    - '%%users.localappdata%%\Microsoft\outlook\*.ost'
    separator: '\'
supported_os: [Windows]
```

collect log
```
2020/05/11 06:52:37 resolve.go:89: users.localappdata resolves to [C:\Users\tatsui\AppData\Local]
2020/05/11 06:52:37 collector.go:158: Collect FILE /C/Users/tatsui/AppData/Local/Microsoft/outlook/tatsui@example.jp.ost
2020/05/11 06:52:37 items.go:54: copy error System FS /C/Users/tatsui/AppData/Local/Microsoft/outlook/tatsui@example.jp.ost -> OsFs Mail\C_User_t_it_AppD_Loca_Micr_outlook_tatsui@example.jp.ost: copy failed: read C:/Users/tatsui/AppData/Local/Microsoft/outlook/tatsui@example.jp.ost: The process cannot access the file because another process has locked a portion of the file.
2020/05/11 06:52:37 run.go:146: Collected Mail in 0.6 seconds
```

**Comment by tatsu-i** [comment]
I'm not sure about the implementation of Go, but I am aware that if StealthOpenFile of NTFSParserDLL was used, the file could be obtained regardless of the file handle.

https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/NTFSParser/NTFSParserDLL/NTFSParserDLL.cpp#L32

**Comment by cugu** [comment]
Thanks for the issue. We also use a raw NTFS parser as fallback if errors occur. I'll try to reproduce the issue tomorrow.

**Comment by cugu** [comment]
This issue appears when the error arises during reading, but the opening of the file succeeded without errors. So the fallback to NTFS is not triggered. Good catch, I'll improve this.

Also those files are good tests for large files. This might need some improvement as well.
