### ISSUE TITLE
Usrclass.dat not collected for all users

### ISSUE THREAD

**Issue by JorahTheExplorer** [forensicanalysis/artifactcollector#66]
Hello, I'm using the following to collect User Registry files

	config := collection.Configuration{
		Artifacts: []string{"WindowsUserRegistryFilesAndTransactionLogs",},
		FS:        fs,
	}

Based on my tests it appears that the above only collects the UsrClass.dat files for accounts that are logged in or for the current users but not for users that are not logged in. 
For the NTUser.dat files, that's works as expected.

I was testing the zip-collector and thank you.

**Comment by JorahTheExplorer** [comment]
I'm not sure if this is by design but I think the issue is here:

resolve.go:89: users.localappdata resolves to [C:\Users\user\AppData\Local]

This works as expected
resolve.go:89: users.userprofile resolves to [%systemroot%\system32\config\systemprofile %systemroot%\ServiceProfiles\LocalService %systemroot%\ServiceProfiles\NetworkService C:\Users\user C:\Users\user1]

**Comment by cugu** [comment]
Thank you for the issue!

`HKEY_USERS\%%users.sid%%\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders` is used to resolve `users.localappdata`. This registry key might not be able to be resolved for other users. I'll add another artifact that provides the path for the other users.

**Comment by cugu** [comment]
Can you update `github.com/forensicanalysis/artifactsgo` to v0.6.5? This should solve the issue. I'll test it tomorrow.

**Comment by JorahTheExplorer** [comment]
Sure thing, I'll test it and report back.

**Comment by JorahTheExplorer** [comment]
Works like a charm, thank you. I'll test a few more scenarios and let you know if there's an issue but other than that this is good to close. Thanks for the quick turn around!
